"""Add teacher salary and user fields

Revision ID: 1db82050ed99
Revises: 6dbbd306d221
Create Date: 2026-02-11 10:12:27.839755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1db82050ed99'
down_revision: Union[str, Sequence[str], None] = '6dbbd306d221'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher_salaries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('teacher_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('paid_by', sa.String(length=36), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teacher_salaries_teacher_id'), 'teacher_salaries', ['teacher_id'], unique=False)
    op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('assigned_classes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'assigned_classes')
    op.drop_column('users', 'address')
    op.drop_column('users', 'phone')
    op.drop_index(op.f('ix_teacher_salaries_teacher_id'), table_name='teacher_salaries')
    op.drop_table('teacher_salaries')
    # ### end Alembic commands ###
